apiVersion: v1
kind: Service
metadata:
  name: health-check-app-services
  labels:
    run: health-check-app-services
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: app-health-check-app
  type: LoadBalancer
